# Generated by Django 3.2.5 on 2022-08-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gview', '0002_auto_20220823_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_type',
            new_name='name',
        ),
    ]
