# Generated by Django 3.2.5 on 2022-08-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gview', '0003_rename_genre_type_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdate',
            name='name',
            field=models.DateField(max_length=3),
        ),
    ]
