# Generated by Django 3.2.5 on 2022-08-22 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gview', '0006_alter_birthdate_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdate',
            name='name',
        ),
        migrations.AddField(
            model_name='birthdate',
            name='date_str',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
