# Generated by Django 3.2.5 on 2022-08-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gview', '0007_auto_20220823_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='birthdate',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Birthdate',
        ),
    ]
