# Generated by Django 3.2.5 on 2022-08-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gview', '0008_auto_20220823_0107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Gender',
        ),
    ]
