# Generated by Django 3.2.5 on 2022-08-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gview', '0009_rename_genre_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identification',
            old_name='genre',
            new_name='gender',
        ),
    ]
